# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: user
  password: 1234

development:
  <<: *default
  database: quote_mobi_development

test: &TEST
  <<: *default
  database: quote_mobi_test

production:
  <<: *default
  database: quote_mobi_production
